# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Address`.
# Please instead update this file by running `bin/tapioca dsl Address`.


class Address
  sig { returns(String) }
  def city; end

  sig { params(value: String).returns(String) }
  def city=(value); end

  sig { returns(String) }
  def street; end

  sig { params(value: String).returns(String) }
  def street=(value); end
end
