# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `InheritanceChildMapper`.
# Please instead update this file by running `bin/tapioca dsl InheritanceChildMapper`.


class InheritanceChildMapper
  sig { returns(Integer) }
  def id; end

  sig { params(value: Integer).returns(Integer) }
  def id=(value); end

  sig { returns(String) }
  def name; end

  sig { params(value: String).returns(String) }
  def name=(value); end
end
