# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `InheritanceBaseMapper`.
# Please instead update this file by running `bin/tapioca dsl InheritanceBaseMapper`.


class InheritanceBaseMapper
  sig { returns(Integer) }
  def id; end

  sig { params(value: Integer).returns(Integer) }
  def id=(value); end
end
