# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `InvalidFieldDefinitionMapper`.
# Please instead update this file by running `bin/tapioca dsl InvalidFieldDefinitionMapper`.


class InvalidFieldDefinitionMapper; end
