# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `NullableMapper`.
# Please instead update this file by running `bin/tapioca dsl NullableMapper`.


class NullableMapper
  sig { returns(T.nilable(String)) }
  def optional_non_nullable; end

  sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
  def optional_non_nullable=(value); end

  sig { returns(T.nilable(String)) }
  def optional_nullable_default; end

  sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
  def optional_nullable_default=(value); end

  sig { returns(String) }
  def required_non_nullable; end

  sig { params(value: String).returns(String) }
  def required_non_nullable=(value); end

  sig { returns(String) }
  def required_non_nullable_default; end

  sig { params(value: String).returns(String) }
  def required_non_nullable_default=(value); end

  sig { returns(T.nilable(String)) }
  def required_nullable; end

  sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
  def required_nullable=(value); end
end
