# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Person`.
# Please instead update this file by running `bin/tapioca dsl Person`.


class Person
  sig { returns(Address) }
  def address; end

  sig { params(value: Address).returns(Address) }
  def address=(value); end

  sig { returns(T::Array[Address]) }
  def addresses; end

  sig { params(value: T::Array[Address]).returns(T::Array[Address]) }
  def addresses=(value); end

  sig { returns(T.nilable(Integer)) }
  def age; end

  sig { params(value: T.nilable(Integer)).returns(T.nilable(Integer)) }
  def age=(value); end

  sig { returns(T.nilable(String)) }
  def email; end

  sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
  def email=(value); end

  sig { returns(T.nilable(T::Array[String])) }
  def friends; end

  sig { params(value: T.nilable(T::Array[String])).returns(T.nilable(T::Array[String])) }
  def friends=(value); end

  sig { returns(T::Boolean) }
  def is_active; end

  sig { params(value: T::Boolean).returns(T::Boolean) }
  def is_active=(value); end

  sig { returns(String) }
  def name; end

  sig { params(value: String).returns(String) }
  def name=(value); end

  sig { returns(Date) }
  def signup_date; end

  sig { params(value: Date).returns(Date) }
  def signup_date=(value); end

  sig { returns(Integer) }
  def user_id; end

  sig { params(value: Integer).returns(Integer) }
  def user_id=(value); end
end
