# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `StrictPersonMapper`.
# Please instead update this file by running `bin/tapioca dsl StrictPersonMapper`.


class StrictPersonMapper
  sig { returns(String) }
  def name; end

  sig { params(value: String).returns(String) }
  def name=(value); end
end
