name: Test
on:
  pull_request:
    branches:
      - "**"
  workflow_dispatch:
  workflow_call:
jobs:
  minitest:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '3.2', '3.3', '3.4', '4.0', truffleruby ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run Minitest
        run: bundle exec rake test
