name: Test & Rspec
on:
  pull_request:
    branches:
      - "**"
  workflow_dispatch:
  workflow_call:
jobs:
  rspec:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '3.1', '3.2', '3.3', jruby, jruby-head, truffleruby, truffleruby-head ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run Rspec test
        run: bundle exec rspec --format progress